# Generated by Django 2.2.13 on 2020-12-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bond_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='legal_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
